### ISSUE TITLE
Does not work with latest dpdk-2.1.0 or git master

### ISSUE THREAD

**Issue by pertoft** [PLVision/dpdkadapter#1]
Hi,

I have tried to compile dpdk-1.7.0 but i continues to fail. Using the latest dpdk-2.1.0 or git master it works flawlessly.

However, the dpdkadapter does not compile with the latest dpdk package.

Any suggestions or plans to make the dpdkadapter compliant with the latest dpdk release?

Thanks
Per
`
root@kvm1-j3484:~/dpdk/ostinato-dpdk/dpdkadapter# make
g++ -I. -I../dpdk/x86_64-native-linuxapp-gcc/include -include ../dpdk/x86_64-native-linuxapp-gcc/include/rte_config.h -g -D__STDC_LIMIT_MACROS -DRTE_MAX_LCORE=64 -DRTE_PKTMBUF_HEADROOM=128 -DRTE_MAX_ETHPORTS=32 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3 -fPIC -c dpdk_adapter.cpp -o dpdk_adapter.o
In file included from dpdk_adapter.cpp:63:0:
dpdk_adapter.cpp: In member function âbool DPDKAdapter::copyMbufToBuf(uint8_t, MBuf_t_, char_, unsigned int&)â:
dpdk_adapter.cpp:1781:58: error: âMBuf_tâ has no member named âpktâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u", pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
                                                          ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1781:5: note: in expansion of macro âqDebugâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u", pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
     ^
dpdk_adapter.cpp:1781:78: error: âMBuf_tâ has no member named âpktâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u", pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
                                                                              ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1781:5: note: in expansion of macro âqDebugâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u", pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
     ^
dpdk_adapter.cpp:1781:99: error: âMBuf_tâ has no member named âpktâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u", pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
                                                                                                   ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1781:5: note: in expansion of macro âqDebugâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u", pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
     ^
dpdk_adapter.cpp:1783:34: error: âMBuf_tâ has no member named âpktâ
     unsigned int segCnt = pMbuf->pkt.nb_segs;
                                  ^
dpdk_adapter.cpp:1787:22: error: âMBuf_tâ has no member named âpktâ
     dataLen = pMbuf->pkt.pkt_len;
                      ^
dpdk_adapter.cpp:1794:45: error: âMBuf_tâ has no member named âpktâ
         rte_memcpy(data + offset, pCurMbuf->pkt.data, pCurMbuf->pkt.data_len);
                                             ^
dpdk_adapter.cpp:1794:65: error: âMBuf_tâ has no member named âpktâ
         rte_memcpy(data + offset, pCurMbuf->pkt.data, pCurMbuf->pkt.data_len);
                                                                 ^
In file included from dpdk_adapter.cpp:63:0:
dpdk_adapter.cpp:1796:53: error: âMBuf_tâ has no member named âpktâ
         qDebug("pkt_len %u, data_len %u", pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len);
                                                     ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1796:9: note: in expansion of macro âqDebugâ
         qDebug("pkt_len %u, data_len %u", pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len);
         ^
dpdk_adapter.cpp:1796:76: error: âMBuf_tâ has no member named âpktâ
         qDebug("pkt_len %u, data_len %u", pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len);
                                                                            ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1796:9: note: in expansion of macro âqDebugâ
         qDebug("pkt_len %u, data_len %u", pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len);
         ^
dpdk_adapter.cpp:1798:29: error: âMBuf_tâ has no member named âpktâ
         offset += pCurMbuf->pkt.data_len;
                             ^
dpdk_adapter.cpp:1799:31: error: âMBuf_tâ has no member named âpktâ
         pNextMbuf = pCurMbuf->pkt.next;
                               ^
dpdk_adapter.cpp: In member function âbool DPDKAdapter::copyBufToMbuf(uint8_t, char_, unsigned int, MBuf_t_&)â:
dpdk_adapter.cpp:1869:12: error: âMBuf_tâ has no member named âpktâ
     pMbuf->pkt.data_len = dataLen < MAX_SEG_SIZE ? dataLen : MAX_SEG_SIZE;
            ^
dpdk_adapter.cpp:1870:12: error: âMBuf_tâ has no member named âpktâ
     pMbuf->pkt.pkt_len = dataLen;
            ^
dpdk_adapter.cpp:1871:12: error: âMBuf_tâ has no member named âpktâ
     pMbuf->pkt.nb_segs = (dataLen / MAX_SEG_SIZE) + ((dataLen % MAX_SEG_SIZE) || 0);
            ^
In file included from dpdk_adapter.cpp:63:0:
dpdk_adapter.cpp:1873:57: error: âMBuf_tâ has no member named âpktâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u",pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
                                                         ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1873:5: note: in expansion of macro âqDebugâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u",pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
     ^
dpdk_adapter.cpp:1873:77: error: âMBuf_tâ has no member named âpktâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u",pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
                                                                             ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1873:5: note: in expansion of macro âqDebugâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u",pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
     ^
dpdk_adapter.cpp:1873:98: error: âMBuf_tâ has no member named âpktâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u",pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
                                                                                                  ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1873:5: note: in expansion of macro âqDebugâ
     qDebug("pkt_len %u, data_len %u, nb_segs %u",pMbuf->pkt.pkt_len, pMbuf->pkt.data_len, pMbuf->pkt.nb_segs);
     ^
dpdk_adapter.cpp:1875:23: error: âMBuf_tâ has no member named âpktâ
     rte_memcpy(pMbuf->pkt.data, data, pMbuf->pkt.data_len);
                       ^
dpdk_adapter.cpp:1875:46: error: âMBuf_tâ has no member named âpktâ
     rte_memcpy(pMbuf->pkt.data, data, pMbuf->pkt.data_len);
                                              ^
dpdk_adapter.cpp:1882:23: error: âMBuf_tâ has no member named âpktâ
     dataLen -= pMbuf->pkt.data_len;
                       ^
dpdk_adapter.cpp:1883:21: error: âMBuf_tâ has no member named âpktâ
     offset = pMbuf->pkt.data_len;
                     ^
dpdk_adapter.cpp:1891:19: error: âMBuf_tâ has no member named âpktâ
         pCurMbuf->pkt.next = DPDKAdapter::instance()->txMbufAlloc(devId);
                   ^
dpdk_adapter.cpp:1892:23: error: âMBuf_tâ has no member named âpktâ
         if (pCurMbuf->pkt.next == NULL)
                       ^
dpdk_adapter.cpp:1898:30: error: âMBuf_tâ has no member named âpktâ
         pCurMbuf = pCurMbuf->pkt.next;
                              ^
dpdk_adapter.cpp:1900:19: error: âMBuf_tâ has no member named âpktâ
         pCurMbuf->pkt.data_len = dataLen < MAX_SEG_SIZE ? dataLen : MAX_SEG_SIZE;
                   ^
In file included from dpdk_adapter.cpp:63:0:
dpdk_adapter.cpp:1902:64: error: âMBuf_tâ has no member named âpktâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u",pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len, pCurMbuf->pkt.nb_segs);
                                                                ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1902:9: note: in expansion of macro âqDebugâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u",pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len, pCurMbuf->pkt.nb_segs);
         ^
dpdk_adapter.cpp:1902:87: error: âMBuf_tâ has no member named âpktâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u",pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len, pCurMbuf->pkt.nb_segs);
                                                                                       ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1902:9: note: in expansion of macro âqDebugâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u",pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len, pCurMbuf->pkt.nb_segs);
         ^
dpdk_adapter.cpp:1902:111: error: âMBuf_tâ has no member named âpktâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u",pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len, pCurMbuf->pkt.nb_segs);
                                                                                                               ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1902:9: note: in expansion of macro âqDebugâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u",pCurMbuf->pkt.pkt_len, pCurMbuf->pkt.data_len, pCurMbuf->pkt.nb_segs);
         ^
dpdk_adapter.cpp:1904:30: error: âMBuf_tâ has no member named âpktâ
         rte_memcpy(pCurMbuf->pkt.data, data + offset, pCurMbuf->pkt.data_len);
                              ^
dpdk_adapter.cpp:1904:65: error: âMBuf_tâ has no member named âpktâ
         rte_memcpy(pCurMbuf->pkt.data, data + offset, pCurMbuf->pkt.data_len);
                                                                 ^
dpdk_adapter.cpp:1906:30: error: âMBuf_tâ has no member named âpktâ
         dataLen -= pCurMbuf->pkt.data_len;
                              ^
dpdk_adapter.cpp:1907:29: error: âMBuf_tâ has no member named âpktâ
         offset += pCurMbuf->pkt.data_len;
                             ^
dpdk_adapter.cpp: In member function âMBuf_t\* DPDKAdapter::cloneMbuf(uint8_t, const MBuf_t_)â:
dpdk_adapter.cpp:1938:26: error: âMBuf_tâ has no member named âpktâ
     rte_memcpy(pMbufOut->pkt.data, pMbufIn->pkt.data, pMbufIn->pkt.data_len);
                          ^
dpdk_adapter.cpp:1938:45: error: âconst MBuf_tâ has no member named âpktâ
     rte_memcpy(pMbufOut->pkt.data, pMbufIn->pkt.data, pMbufIn->pkt.data_len);
                                             ^
dpdk_adapter.cpp:1938:64: error: âconst MBuf_tâ has no member named âpktâ
     rte_memcpy(pMbufOut->pkt.data, pMbufIn->pkt.data, pMbufIn->pkt.data_len);
                                                                ^
dpdk_adapter.cpp:1939:15: error: âMBuf_tâ has no member named âpktâ
     pMbufOut->pkt.nb_segs = pMbufIn->pkt.nb_segs;
               ^
dpdk_adapter.cpp:1939:38: error: âconst MBuf_tâ has no member named âpktâ
     pMbufOut->pkt.nb_segs = pMbufIn->pkt.nb_segs;
                                      ^
dpdk_adapter.cpp:1940:15: error: âMBuf_tâ has no member named âpktâ
     pMbufOut->pkt.data_len = pMbufIn->pkt.data_len;
               ^
dpdk_adapter.cpp:1940:39: error: âconst MBuf_tâ has no member named âpktâ
     pMbufOut->pkt.data_len = pMbufIn->pkt.data_len;
                                       ^
dpdk_adapter.cpp:1941:15: error: âMBuf_tâ has no member named âpktâ
     pMbufOut->pkt.pkt_len = pMbufIn->pkt.pkt_len;
               ^
dpdk_adapter.cpp:1941:38: error: âconst MBuf_tâ has no member named âpktâ
     pMbufOut->pkt.pkt_len = pMbufIn->pkt.pkt_len;
                                      ^
dpdk_adapter.cpp:1944:35: error: âconst MBuf_tâ has no member named âpktâ
     MBuf_t_ pCurMbufIn = pMbufIn->pkt.next;
                                   ^
dpdk_adapter.cpp:1948:22: error: âMBuf_tâ has no member named âpktâ
         pCurMbufOut->pkt.next = DPDKAdapter::instance()->txMbufAlloc(devId);
                      ^
dpdk_adapter.cpp:1955:36: error: âMBuf_tâ has no member named âpktâ
         pCurMbufOut = pCurMbufOut->pkt.next;
                                    ^
In file included from dpdk_adapter.cpp:63:0:
dpdk_adapter.cpp:1957:67: error: âMBuf_tâ has no member named âpktâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u", pCurMbufIn->pkt.pkt_len, pCurMbufIn->pkt.data_len, pCurMbufIn->pkt.nb_segs);
                                                                   ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1957:9: note: in expansion of macro âqDebugâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u", pCurMbufIn->pkt.pkt_len, pCurMbufIn->pkt.data_len, pCurMbufIn->pkt.nb_segs);
         ^
dpdk_adapter.cpp:1957:92: error: âMBuf_tâ has no member named âpktâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u", pCurMbufIn->pkt.pkt_len, pCurMbufIn->pkt.data_len, pCurMbufIn->pkt.nb_segs);
                                                                                            ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1957:9: note: in expansion of macro âqDebugâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u", pCurMbufIn->pkt.pkt_len, pCurMbufIn->pkt.data_len, pCurMbufIn->pkt.nb_segs);
         ^
dpdk_adapter.cpp:1957:118: error: âMBuf_tâ has no member named âpktâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u", pCurMbufIn->pkt.pkt_len, pCurMbufIn->pkt.data_len, pCurMbufIn->pkt.nb_segs);
                                                                                                                      ^
dpdk_log.h:36:91: note: in definition of macro âLogTraceâ
 #define LogTrace(fmt, ...) _Log(LOG_LEVEL_TRACE, __FILE__, **LINE**, **FUNCTION**, fmt, ##**VA_ARGS**)
                                                                                           ^
dpdk_adapter.cpp:1957:9: note: in expansion of macro âqDebugâ
         qDebug("pkt_len %u, data_len %u, nb_segs %u", pCurMbufIn->pkt.pkt_len, pCurMbufIn->pkt.data_len, pCurMbufIn->pkt.nb_segs);
         ^
dpdk_adapter.cpp:1959:33: error: âMBuf_tâ has no member named âpktâ
         rte_memcpy(pCurMbufOut->pkt.data, pCurMbufIn->pkt.data, pCurMbufIn->pkt.data_len);
                                 ^
dpdk_adapter.cpp:1959:55: error: âMBuf_tâ has no member named âpktâ
         rte_memcpy(pCurMbufOut->pkt.data, pCurMbufIn->pkt.data, pCurMbufIn->pkt.data_len);
                                                       ^
dpdk_adapter.cpp:1959:77: error: âMBuf_tâ has no member named âpktâ
         rte_memcpy(pCurMbufOut->pkt.data, pCurMbufIn->pkt.data, pCurMbufIn->pkt.data_len);
                                                                             ^
dpdk_adapter.cpp:1960:22: error: âMBuf_tâ has no member named âpktâ
         pCurMbufOut->pkt.nb_segs = pCurMbufIn->pkt.nb_segs;
                      ^
dpdk_adapter.cpp:1960:48: error: âMBuf_tâ has no member named âpktâ
         pCurMbufOut->pkt.nb_segs = pCurMbufIn->pkt.nb_segs;
                                                ^
dpdk_adapter.cpp:1961:22: error: âMBuf_tâ has no member named âpktâ
         pCurMbufOut->pkt.data_len = pCurMbufIn->pkt.data_len;
                      ^
dpdk_adapter.cpp:1961:49: error: âMBuf_tâ has no member named âpktâ
         pCurMbufOut->pkt.data_len = pCurMbufIn->pkt.data_len;
                                                 ^
dpdk_adapter.cpp:1962:22: error: âMBuf_tâ has no member named âpktâ
         pCurMbufOut->pkt.pkt_len = pCurMbufIn->pkt.pkt_len;
                      ^
dpdk_adapter.cpp:1962:48: error: âMBuf_tâ has no member named âpktâ
         pCurMbufOut->pkt.pkt_len = pCurMbufIn->pkt.pkt_len;
                                                ^
dpdk_adapter.cpp:1964:34: error: âMBuf_tâ has no member named âpktâ
         pCurMbufIn = pCurMbufIn->pkt.next;
                                  ^
dpdk_adapter.cpp: In member function âvoid DPDKAdapter::saveToBuf(uint8_t, MBuf_t*_, uint8_t)â:
dpdk_adapter.cpp:2000:25: error: âMBuf_tâ has no member named âpktâ
         hdr.caplen = m->pkt.data_len;
                         ^
dpdk_adapter.cpp:2003:55: error: âMBuf_tâ has no member named âpktâ
         if(devInfo.captureDataSize + sizeof(hdr) + m->pkt.data_len > devInfo.captureDataLength)
                                                       ^
dpdk_adapter.cpp:2012:66: error: âMBuf_tâ has no member named âpktâ
         memcpy(devInfo.captureData + devInfo.captureDataSize, m->pkt.data, m->pkt.data_len);
                                                                  ^
dpdk_adapter.cpp:2012:79: error: âMBuf_tâ has no member named âpktâ
         memcpy(devInfo.captureData + devInfo.captureDataSize, m->pkt.data, m->pkt.data_len);
                                                                               ^
dpdk_adapter.cpp:2013:39: error: âMBuf_tâ has no member named âpktâ
         devInfo.captureDataSize += m->pkt.data_len;
                                       ^
Makefile:45: recipe for target 'dpdk_adapter.o' failed
make: *_\* [dpdk_adapter.o] Error 1
root@kvm1-j3484:~/dpdk/ostinato-dpdk/dpdkadapter#

`
